# GolfCraft Configuration
#
# USE 4 SPACES INSTEAD OF TABS

kill-mobs-on-course: true
enable-clubs: true
number-of-bounces: 3
ball-power-percentage: 100
enable-speed-variances: true
rough-min-percent-decrease: 20
rough-max-percent-decrease: 40
sandtrap-min-percent-decrease: 60
sandtrap-max-percent-decrease: 80
teeing-ground-min-percent-increase: 100
teeing-ground-max-percent-increase: 130
landed-block:
  sand-trap:
    "SAND": -1
    "SOUL_SAND": -1
  rough:
    "GRASS": -1
    "STAINED_CLAY": 14
  fairway:
    "WOOL": 13
  green:
    "WOOL": 5
  hole:
    "GLOWSTONE": -1
  tee:
    "WOOD": -1
  ob:
    "LEAVES": -1
    "NETHERRACK": -1
    "BARRIER": -1
club-speed:
  rough:
    0: 0.9
    1: 0.86
    11: 0.3
  sand-trap:
    0: 0.35
    1: 0.35
    2: 0.35
    3: 0.6
    4: 0.6
    5: 0.6
    6: 0.6
    7: 0.6
    8: 0.6
    9: 0.6
    10: 0.6
    11: 0.2
  tee:
    0: 1.63
    1: 1.49
    2: 1.35
  fairway:
    0: 1.25
    1: 1.2
    2: 1.15
    3: 1.24
    4: 1.18
    5: 1.12
    6: 1.06
    7: 1.0
    8: 0.93
    9: 0.85
    10: 0.6
    11: 0.45
max-leap:
  tee:
    0: "140(123)"
    1: "130(112)"
    2: "120(104)"
    3: "108(93)"
    4: "101(87)"
    5: "94(81)"
    6: "88(74)"
    7: "81(69)"
    8: "73(62)"
    9: "66(56)"
    10: "39(31)"
    11: "27(22)"
  fairway:
    0: "96(84)"
    1: "94(80)"
    2: "95(81)"
    3: "108(94)"
    4: "101(87)"
    5: "94(81)"
    6: "88(74)"
    7: "81(69)"
    8: "73(62)"
    9: "66(56)"
    10: "39(31)"
    11: "27(22)"
  rough:
    0: "57(46)"
    1: "56(46)"
    2: "95(81)"
    3: "108(93)"
    4: "101(87)"
    5: "94(81)"
    6: "88(74)"
    7: "81(69)"
    8: "73(62)"
    9: "66(56)"
    10: "39(31)"
    11: "14(11)"
  sand-trap:
    0: "13(9)"
    1: "14(10)"
    2: "15(11)"
    3: "35(28)"
    4: "36(28)"
    5: "36(29)"
    6: "26(29)"
    7: "37(30)"
    8: "37(30)"
    9: "39(31)"
    10: "49(40)"
    11: "8(5)"
